### ISSUE TITLE
how can I replace get_shape_details for shape file? 

### ISSUE THREAD

**Issue by msdakot** [jbaileyh/geogrid#15]
I have a shape file and not a json file. So, when I do st_read, it doesn't read get_shape_details (since it is associated with read_polygons but read_polygons doesn't read shp files). What command should I use to get the details ?

Thank you in advance!

**Comment by msdakot** [comment]
Also it keeps showing too few polygons (I am dealing with US county level data

**Comment by sassalley** [comment]
Hi @msdakot,
Thanks for trying the package!

Have you tried using `read_polygons` on your shapefile?  `read_polygons` uses st_read which I believe is capable of reading shapefiles.

**Comment by jbaileyh** [comment]
Hi @msdakot is this still proving an issue? If not I will close. Thanks.

**Comment by msdakot** [comment]
@jbaileyh Thank you very much for responding to my queries! No, it running perfectly now.

Thank you once again for creating this package.
