### ISSUE TITLE
Function clean() not found

### ISSUE THREAD

**Issue by lhehnke** [jbaileyh/geogrid#23]
Hi Joseph,

I'm planning on using geogrid for a new project but I couldn't manage to plot the final results. I'm adapting your sample code and while _calculate_grid()_  and _assign_polygons()_ both work perfectly fine, _clean()_ results in an error message (_Error in clean(resulthex) : could not find function "clean"_).

Do you have any ideas on how to fix/bypass this? Thanks in advance! :-)

**Comment by jbaileyh** [comment]
Hi @lhehnke 

Glad to hear you're planning on using and thanks for raising the issue!

I believe it should be documented in the second code block of the [Example](https://github.com/jbaileyh/geogrid#example) in the README but I admit it may not be clear. The function is just something that I used to re-shape the data for use with ggplot2. 

For quick reference here it is again:

```
clean <- function(shape) {
  shape@data$id = rownames(shape@data)
  shape.points = fortify(shape, region="id")
  shape.df = merge(shape.points, shape@data, by="id")
}
```
Hope this helps!

**Comment by lhehnke** [comment]
Thanks helping, you're absolutely right.

**Comment by jbaileyh** [comment]
Good luck with the project!
